language: ruby
cache: bundler
rvm:
  - 2.2.2
  - 1.9.3
  - jruby
gemfile:
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-4.2
  - Gemfile
script: bundle exec rspec
